# This file is NOT to be used for production, only for development.

version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./server/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./server/
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./server/app:/server/app:z
    working_dir: /server
    env_file:
      - ./server/.env
    depends_on:
      db:
        condition: service_healthy
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/server/app"]

  frontend:
    build:
      context: ./planit/
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    env_file:
      - ./planit/.env
    volumes:
      - ./planit:/app:z
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  postgres_data:
