from .chat_message_model import ChatMessage
from .course_model import Course
from .evaluation_model import Evaluation
from .event_model import Event
from .file_model import File
from .lecture_model import Lecture
from .operation_model import Operation
from .routine_model import Routine
from .user_model import User
