name: Frontend CI Build

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - developer
    paths:
      - 'planit/**'
  pull_request:
    branches:
      - main
      - developer
    paths:
      - 'planit/**'

  workflow_dispatch:

jobs:
  frontend-ci:
    name: Frontend CI Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./planit
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: planit/package-lock.json

      - name: Install Frontend Dependencies
        run: npm --prefix planit ci

      - name: Build Frontend
        env:
          VITE_FIREBASE_API_KEY: ""
          VITE_FIREBASE_AUTH_DOMAIN: ""
          VITE_FIREBASE_PROJECT_ID: ""
          VITE_FIREBASE_STORAGE_BUCKET: ""
          VITE_FIREBASE_MESSAGING_SENDER_ID: ""
          VITE_FIREBASE_APP_ID: ""
        run: npm --prefix planit run build
