name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'firebase.json'
      - '.github/workflows/deploy-frontend.yml'

  workflow_dispatch:

env:
  PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  REGION: ${{ vars.GCP_REGION }}
  SERVICE_NAME: ${{ vars.GCP_SERVICE_NAME }}
  FIREBASE_SERVICE_KEY: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}'

jobs:
  build-and-deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Frontend Dependencies
        run: npm --prefix frontend ci

      - name: Build Frontend
        run: npm --prefix frontend run build

      - name: Configure Firebase JSON
        run: |
          sed -i 's/__SERVICE_ID__/${{ env.SERVICE_NAME }}/g' firebase.json
          sed -i 's/__REGION__/${{ env.REGION }}/g' firebase.json

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ env.FIREBASE_SERVICE_KEY }}'
          channelId: live
          projectId: ${{ env.PROJECT_ID }}
