name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches:
      - main
    paths:
      - 'planit/**'
      - 'firebase.json'
      - '.github/workflows/deploy-frontend.yml'

  workflow_dispatch:

env:
  PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  REGION: ${{ vars.GCP_REGION }}
  SERVICE_NAME: ${{ vars.GCP_SERVICE_NAME }}
  WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
  SERVICE_ACCOUNT: ${{ secrets.GCP_SA_EMAIL }}

jobs:
  build-and-deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: planit/package-lock.json

      - name: Install Frontend Dependencies
        run: npm --prefix planit ci

      - name: Build Frontend
        run: npm --prefix planit run build

      - name: Configure Firebase JSON
        run: |
          sed -i 's/__SERVICE_ID__/${{ env.SERVICE_NAME }}/g' firebase.json
          sed -i 's/__REGION__/${{ env.REGION }}/g' firebase.json

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          channelId: live
          projectId: ${{ env.PROJECT_ID }}
