name: Backend CI Tests

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - developer
    paths:
      - 'server/**'
  pull_request:
    branches:
      - main
      - developer
    paths:
      - 'server/**'

jobs:
  backend-ci:
    name: Backend CI Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    env:
      DATABASE_URL: "sqlite:///:memory:"
      GOOGLE_API_KEY: "dummy_key"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.5'

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run tests
        run: pytest
